[package]
name = "capybar"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31.10"
wayland-protocols = "0.32.8"

fontconfig = "0.9.0"
fontdue = "0.9.3"

chrono = "0.4.41"
