#TOML does not support variables interpolation, so this is just a place to copy values from 
[palete]
    font = 0xf5e0dcff
    background = 0x1e1e2eff
    border = 0x74c7ecff

[preloaded_fonts]
    list = ["mono", "jetbrainsmononerdfont"]

[bar.settings]
    width = 1920
    background = 0x1e1e2eff
    border = [1, 0x74c7ecff]
    padding = [5,5,5]
    [bar.settings.left_settings]
        margin = [3,0,3,3]
    [bar.settings.right_settings]
        margin = [0,6,3,3]

[[bar.left]]
    widget = "keyboard"
    [[bar.left.settings]]
    size = 24
    font_color = 0xf5e0dcff
    layout_mappings = {"Russian" = "RU", "English (US)" = "EN"}
    border = [1, 0x74c7ecff]
    [[bar.left.settings]]
    update_rate = 100

[[bar.left]]
    widget = "cpu"
    [bar.left.settings]
    size = 24
    font_color = 0xf5e0dcff
    border = [1, 0x74c7ecff]

[[bar.center]]
    widget = "clock"
    [bar.center.settings] 
    size = 24
    font_color = 0xf5e0dcff
    margin = [0,3,3,0]
    border = [1, 0x74c7ecff]

[[bar.right]]
    widget = "battery"
    [bar.right.settings] 
    size = 24
    font_color = 0xf5e0dcff
    margin = [0,3,3,0]
    border = [1, 0x74c7ecff]
