[default-style]
background = 0x1e1e2eff
border = 0x74c7ecff
font = 0xf5e0dcff

[bar]
background.enable = true
background.color = 0x313244ff
border.enable = true

[battery]
background.enable = true

[clock]
background.enable = true

[CPU]
background.enable = true
